### ISSUE TITLE
foldp' breaks debugger in 0.15?

### ISSUE THREAD

**Issue by Morendil** [Apanatshka/elm-signal-extra#11]
The code below now (0.15) results in the following Javascript error when loaded with ?debug

```
Cannot read property 'ctor' of undefined
```

Single-stepping under the JS debugger narrows down the source of the problem: the function "start" is translated into a JS function which is called, upon startup, with an undefined parameter.

```
import Graphics.Element exposing (..)

import Window
import Signal
import Signal.Extra

start signal =
    {}

update signal state =
    state

display anything =
    empty

inputs = Window.dimensions

main =
    let states = Signal.Extra.foldp' update start inputs
    in Signal.map display states
```

**Comment by Apanatshka** [comment]
Have you tried inlining `foldp'` and finding out where it goes wrong in there? It's normal Elm code, so this is more than likely a compiler bug.

**Comment by jvoigtlaender** [comment]
FWIW, my guess:

`foldp'` is defined in terms of `merge`. In the 2.0.0 release of `core`, the `merge` function had a broken initial value. That was fixed only lately in [this commit](https://github.com/elm-lang/core/commit/8ca34a7827598b87eb7511a943b6050f2408515a).

@Morendil, can you make sure that you use the 2.0.1 release of `core` and check whether the problem persists?

**Comment by Morendil** [comment]
I've required versions 2.0.1 of core and 4.0.1 of elm-signal-extra, and the problem persists.

I'm not sure this is related to the merge issue - it's not a bogus value that shows up but a null (undefined) value, and only under the debugger.

OTOH, I do agree this looks more like a bug in the compiler or debugger - possibly not the right project to file the bug against.

**Comment by jvoigtlaender** [comment]
What I (still) conjecture: It _is_ the merge issue. The problem there was exactly that prior to the commit I referenced, merged signals would have an undefined value. So why is the error still showing up? And only in debug mode, not otherwise? Maybe the debugger is using version 2.0.0 of `core`? I remember that there was some issue in the past with updating the `core` dependency of a project not necessarily meaning that the running `elm-reactor` instance would use that version as well.

Obviously: best to ask Evan.

**Comment by Morendil** [comment]
Should I take it to the mailing list, or is it sufficient to @evancz here?

**Comment by jvoigtlaender** [comment]
Maybe opening an issue against the `elm-reactor` repo. Maybe along with a link to [this earlier comment](https://github.com/elm-lang/core/pull/76#issuecomment-70923371). The situation in both cases, to me, looks like:
- There's a bug in `core`.
- The bug gets fixed.
- If one uses `elm-reactor` in debug mode, then the older version of `core` gets run that was current when that `elm-reactor` version was released/installed.

Which means two things:
- It's not really possible to check whether the fix in `core` works well also under hot-swapping, pause/rewind etc. (Which was the problem in that older discussion, because the fix back then was about timing semantics, which might have an interaction with hot-swapping etc.)
- It's not really possible for users to rely on the debug mode until the next version of `elm-reactor` is released. Because if their program contains code affected by the fix to `core`, then running the program in non-debug mode will use the fixed `core` variant, while running the program in debug mode will use the `core` variant without that fix. (Which I think is the problem @Morendil hit here.)

**Comment by Morendil** [comment]
@jvoigtlaender OK, knowing where to look made it easier: I can confirm that it's version 2.0.0 of core I see when I debug the Elm debugger under the JS debugger.

I'll file this as a new issue against elm-reactor.
